#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Sep 15, 2019 07:11:20 PM +0630  platform: Darwin
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #a6ddf4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 868x507+321+158
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1440 784
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab49 \
        -activebackground #a6ddf4 -activeforeground #1c38ed \
        -background #a6ddf4 -font {-family {Al Bayan} -size 20 -weight bold} \
        -foreground #171fff -highlightbackground #ffffffffffff \
        -highlightcolor #2b1582 \
        -text {Welcome to Software Defect Prediction System} 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra50 \
        -borderwidth 2 -relief groove -background #21b5ff -height 525 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 225 
    vTcl:DefineAlias "$top.fra50" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra50
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #21b5ff \
        -font {-family {Al Bayan} -size 20 -weight bold} -foreground white \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {SDP System} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -font {-family {Al Bayan} -size 16} \
        -foreground blue -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -relief raised \
        -text Preprocessing 
    vTcl:DefineAlias "$site_3_0.but65" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -font {-family {Al Bayan} -size 16} \
        -foreground blue -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -relief raised \
        -text {Dataset Selection} 
    vTcl:DefineAlias "$site_3_0.but66" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -font {-family {Al Bayan} -size 16} \
        -foreground blue -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -relief raised \
        -text Discretization 
    vTcl:DefineAlias "$site_3_0.but67" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -font {-family {Al Bayan} -size 16} \
        -foreground blue -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -relief raised \
        -text {Feature Selection} 
    vTcl:DefineAlias "$site_3_0.but69" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -font {-family {Al Bayan} -size 16} \
        -foreground blue -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -overrelief flat -relief raised \
        -text {Project Info} 
    vTcl:DefineAlias "$site_3_0.but70" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -font {-family {Al Bayan} -size 16} \
        -foreground blue -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -relief raised \
        -text {Model Selection} 
    vTcl:DefineAlias "$site_3_0.but71" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -font {-family {Al Bayan} -size 16} \
        -foreground blue -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -relief raised -text Outcome 
    vTcl:DefineAlias "$site_3_0.but72" "Button7" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 40 -y 30 -width 141 -relwidth 0 -height 52 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -y 220 -width 227 -relwidth 0 -height 62 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but66 \
        -in $site_3_0 -x 0 -y 160 -width 227 -relwidth 0 -height 62 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 0 -y 280 -width 227 -relwidth 0 -height 62 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 0 -y 340 -width 227 -relwidth 0 -height 62 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 0 -y 100 -width 227 -relwidth 0 -height 62 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 0 -y 400 -width 227 -relwidth 0 -height 62 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but72 \
        -in $site_3_0 -x 0 -y 460 -width 227 -relwidth 0 -height 62 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #a6ddf4 \
        -font {-family {Al Bayan} -size 16} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Project Description :} 
    vTcl:DefineAlias "$top.lab56" "Label3" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes75 \
        -background #a6ddf4 -font {-family {Al Bayan} -size 16} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {          Software Defect Prediction mechanisms are used to enhance the work of SQA process through the prediction of defect modules comprised with 5 stages :} \
        -width 623 
    vTcl:DefineAlias "$top.mes75" "Message1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab79 \
        -activebackground #f9f9f9 -activeforeground black -background #a6ddf4 \
        -font {-family {Al Bayan} -size 16} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {1. Preprocessing      :   Remove null value, missing value and impossible instance
} 
    vTcl:DefineAlias "$top.lab79" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab80 \
        -activebackground #f9f9f9 -activeforeground black -background #a6ddf4 \
        -font {-family {Al Bayan} -size 16} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left \
        -text {2. Discretization        :   Convert continuous data values into finite set of values} 
    vTcl:DefineAlias "$top.lab80" "Label5" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes82 \
        -background #a6ddf4 -font {-family {Al Bayan} -size 16} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {4. Model Building      :   Adaptive Boosting based on Support Vector Machine-Radial Basis Function} \
        -width 625 
    vTcl:DefineAlias "$top.mes82" "Message2" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes84 \
        -background #a6ddf4 -font {-family {Al Bayan} -size 16} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {3. Feature Selection :  Select features using Minimum Redundancy and Maximum Relevance (MRMR)} \
        -width 624 
    vTcl:DefineAlias "$top.mes84" "Message3" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes85 \
        -background #a6ddf4 -font {-family {Al Bayan} -size 16} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {5. Comparison          :  Accuracy and performance measures used to compare with hybrid method against single classifier results} \
        -width 624 
    vTcl:DefineAlias "$top.mes85" "Message4" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab49 \
        -in $top -x 330 -y 26 -width 475 -relwidth 0 -height 46 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 0 -y -10 -width 225 -relwidth 0 -height 525 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 230 -y 104 -width 161 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.mes75 \
        -in $top -x 230 -y 146 -width 623 -relwidth 0 -height 53 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab79 \
        -in $top -x 236 -y 226 -width 595 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab80 \
        -in $top -x 231 -y 264 -width 586 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes82 \
        -in $top -x 230 -y 378 -width 625 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes84 \
        -in $top -x 227 -y 314 -width 624 -relwidth 0 -height 43 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes85 \
        -in $top -x 225 -y 437 -width 624 -relwidth 0 -height 58 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

