#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 15, 2019 07:11:19 PM +0630  platform: Darwin

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ui1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    ui1_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    ui1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("868x507+321+158")
        top.title("New Toplevel")
        top.configure(background="#a6ddf4")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.38, rely=0.049, height=46, width=475)
        self.Label1.configure(activebackground="#a6ddf4")
        self.Label1.configure(activeforeground="#1c38ed")
        self.Label1.configure(background="#a6ddf4")
        self.Label1.configure(font="-family {Al Bayan} -size 20 -weight bold")
        self.Label1.configure(foreground="#171fff")
        self.Label1.configure(highlightbackground="#ffffffffffff")
        self.Label1.configure(highlightcolor="#2b1582")
        self.Label1.configure(text='''Welcome to Software Defect Prediction System''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=-0.02, relheight=1.036, relwidth=0.259)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#21b5ff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.178, rely=0.057, height=52, width=141)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#21b5ff")
        self.Label2.configure(font="-family {Al Bayan} -size 20 -weight bold")
        self.Label2.configure(foreground="white")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''SDP System''')

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.0, rely=0.419, height=62, width=227)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(font="-family {Al Bayan} -size 16")
        self.Button2.configure(foreground="blue")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(justify='left')
        self.Button2.configure(relief="raised")
        self.Button2.configure(text='''Preprocessing''')

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.0, rely=0.305, height=62, width=227)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(font="-family {Al Bayan} -size 16")
        self.Button3.configure(foreground="blue")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(justify='left')
        self.Button3.configure(relief="raised")
        self.Button3.configure(text='''Dataset Selection''')

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.0, rely=0.533, height=62, width=227)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(font="-family {Al Bayan} -size 16")
        self.Button4.configure(foreground="blue")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(justify='left')
        self.Button4.configure(relief="raised")
        self.Button4.configure(text='''Discretization''')

        self.Button5 = tk.Button(self.Frame1)
        self.Button5.place(relx=0.0, rely=0.648, height=62, width=227)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(font="-family {Al Bayan} -size 16")
        self.Button5.configure(foreground="blue")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(justify='left')
        self.Button5.configure(relief="raised")
        self.Button5.configure(text='''Feature Selection''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.0, rely=0.19, height=62, width=227)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(font="-family {Al Bayan} -size 16")
        self.Button1.configure(foreground="blue")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(justify='left')
        self.Button1.configure(overrelief="flat")
        self.Button1.configure(relief="raised")
        self.Button1.configure(text='''Project Info''')

        self.Button6 = tk.Button(self.Frame1)
        self.Button6.place(relx=0.0, rely=0.762, height=62, width=227)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(font="-family {Al Bayan} -size 16")
        self.Button6.configure(foreground="blue")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(justify='left')
        self.Button6.configure(relief="raised")
        self.Button6.configure(text='''Model Selection''')

        self.Button7 = tk.Button(self.Frame1)
        self.Button7.place(relx=0.0, rely=0.876, height=62, width=227)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(font="-family {Al Bayan} -size 16")
        self.Button7.configure(foreground="blue")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(justify='left')
        self.Button7.configure(relief="raised")
        self.Button7.configure(text='''Outcome''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.265, rely=0.197, height=31, width=161)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#a6ddf4")
        self.Label3.configure(font="-family {Al Bayan} -size 16")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Project Description :''')

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.265, rely=0.286, relheight=0.105
                , relwidth=0.718)
        self.Message1.configure(background="#a6ddf4")
        self.Message1.configure(font="-family {Al Bayan} -size 16")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Software Defect Prediction mechanisms are used to enhance the work of SQA process through the prediction of defect modules comprised with 5 stages :''')
        self.Message1.configure(width=623)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.271, rely=0.444, height=41, width=595)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#a6ddf4")
        self.Label4.configure(font="-family {Al Bayan} -size 16")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''1. Preprocessing      :   Remove null value, missing value and impossible instance''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.265, rely=0.513, height=31, width=586)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#a6ddf4")
        self.Label5.configure(font="-family {Al Bayan} -size 16")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(justify='left')
        self.Label5.configure(text='''2. Discretization        :   Convert continuous data values into finite set of values''')

        self.Message2 = tk.Message(top)
        self.Message2.place(relx=0.265, rely=0.74, relheight=0.099
                , relwidth=0.72)
        self.Message2.configure(background="#a6ddf4")
        self.Message2.configure(font="-family {Al Bayan} -size 16")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''4. Model Building      :   Adaptive Boosting based on Support Vector Machine-Radial Basis Function''')
        self.Message2.configure(width=625)

        self.Message3 = tk.Message(top)
        self.Message3.place(relx=0.259, rely=0.611, relheight=0.085
                , relwidth=0.719)
        self.Message3.configure(background="#a6ddf4")
        self.Message3.configure(font="-family {Al Bayan} -size 16")
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(text='''3. Feature Selection :  Select features using Minimum Redundancy and Maximum Relevance (MRMR)''')
        self.Message3.configure(width=624)

        self.Message4 = tk.Message(top)
        self.Message4.place(relx=0.259, rely=0.858, relheight=0.114
                , relwidth=0.719)
        self.Message4.configure(background="#a6ddf4")
        self.Message4.configure(font="-family {Al Bayan} -size 16")
        self.Message4.configure(foreground="#000000")
        self.Message4.configure(highlightbackground="#d9d9d9")
        self.Message4.configure(highlightcolor="black")
        self.Message4.configure(text='''5. Comparison          :  Accuracy and performance measures used to compare with hybrid method against single classifier results''')
        self.Message4.configure(width=624)

if __name__ == '__main__':
    vp_start_gui()





