#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 15, 2019 11:39:51 PM +0630  platform: Darwin

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ui4_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    ui4_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    ui4_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font14 = "-family {Al Bayan} -size 16 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font15 = "-family {Al Bayan} -size 16 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("868x507+329+129")
        top.title("New Toplevel")
        top.configure(background="#a6ddf4")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=-0.02, relheight=1.036, relwidth=0.259)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#21b5ff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.178, rely=0.057, height=52, width=141)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#21b5ff")
        self.Label2.configure(font="-family {Al Bayan} -size 20 -weight bold")
        self.Label2.configure(foreground="white")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''SDP System''')

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.0, rely=0.419, height=62, width=227)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(font="-family {Al Bayan} -size 16")
        self.Button2.configure(foreground="blue")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(justify='left')
        self.Button2.configure(relief="raised")
        self.Button2.configure(text='''Preprocessing''')

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.0, rely=0.305, height=62, width=227)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(font="-family {Al Bayan} -size 16")
        self.Button3.configure(foreground="blue")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(justify='left')
        self.Button3.configure(relief="raised")
        self.Button3.configure(text='''Dataset Selection''')

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.0, rely=0.533, height=62, width=227)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(font="-family {Al Bayan} -size 16")
        self.Button4.configure(foreground="blue")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(justify='left')
        self.Button4.configure(relief="raised")
        self.Button4.configure(text='''Discretization''')

        self.Button5 = tk.Button(self.Frame1)
        self.Button5.place(relx=0.0, rely=0.648, height=62, width=227)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(font="-family {Al Bayan} -size 16")
        self.Button5.configure(foreground="blue")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(justify='left')
        self.Button5.configure(relief="raised")
        self.Button5.configure(text='''Feature Selection''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.0, rely=0.19, height=62, width=227)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(font="-family {Al Bayan} -size 16")
        self.Button1.configure(foreground="blue")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(justify='left')
        self.Button1.configure(overrelief="flat")
        self.Button1.configure(relief="raised")
        self.Button1.configure(text='''Project Info''')

        self.Button6 = tk.Button(self.Frame1)
        self.Button6.place(relx=0.0, rely=0.762, height=62, width=227)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(font="-family {Al Bayan} -size 16")
        self.Button6.configure(foreground="blue")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(justify='left')
        self.Button6.configure(relief="raised")
        self.Button6.configure(text='''Model Selection''')

        self.Button7 = tk.Button(self.Frame1)
        self.Button7.place(relx=0.0, rely=0.876, height=62, width=227)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(font="-family {Al Bayan} -size 16")
        self.Button7.configure(foreground="blue")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(justify='left')
        self.Button7.configure(relief="raised")
        self.Button7.configure(text='''Outcome''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.259, rely=-0.02, relheight=1.016
                , relwidth=0.743)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#a6ddf4")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.341, rely=0.214, height=31, width=216)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#a6ddf4")
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(font=font15)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(justify='left')
        self.Label1.configure(text='''PC1 dataset using SVM''')

        self.Label3 = tk.Label(self.Frame2)
        self.Label3.place(relx=0.147, rely=0.058, height=39, width=472)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#a6ddf4")
        self.Label3.configure(font="-family {Al Bayan} -size 20 -weight bold")
        self.Label3.configure(foreground="blue")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Welcome to Software Defect Prediction System''')

        self.Label4 = tk.Label(self.Frame2)
        self.Label4.place(relx=0.023, rely=0.311, height=31, width=85)
        self.Label4.configure(background="#a6ddf4")
        self.Label4.configure(font=font14)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Accuracy :''')

        self.Label5 = tk.Label(self.Frame2)
        self.Label5.place(relx=0.016, rely=0.447, height=31, width=96)
        self.Label5.configure(background="#a6ddf4")
        self.Label5.configure(font=font14)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(justify='left')
        self.Label5.configure(text='''Precision :''')

        self.Label6 = tk.Label(self.Frame2)
        self.Label6.place(relx=0.031, rely=0.583, height=31, width=61)
        self.Label6.configure(background="#a6ddf4")
        self.Label6.configure(font=font14)
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Recall :''')

        self.Label7 = tk.Label(self.Frame2)
        self.Label7.place(relx=0.031, rely=0.718, height=31, width=73)
        self.Label7.configure(background="#a6ddf4")
        self.Label7.configure(font=font14)
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''F-score :''')

        self.Label8 = tk.Label(self.Frame2)
        self.Label8.place(relx=0.031, rely=0.854, height=31, width=147)
        self.Label8.configure(background="#a6ddf4")
        self.Label8.configure(font=font14)
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Confusion Matrix :''')

        self.Frame3 = tk.Frame(self.Frame2)
        self.Frame3.place(relx=0.45, rely=0.369, relheight=0.417, relwidth=0.457)

        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





